### ISSUE TITLE
file incomplete after disconnect

### ISSUE THREAD

**Issue by Angel203** [R3DST0RM/MediaDownloader#8]
After a disconnect / WLAN issue, the current donwload finishes although it is incomplete. 
Missing detection of an incomplete donwload

**Comment by R3DST0RM** [comment]
Committed a test patch which supports to resume a download after closing the program. Supported downloaders are: soundcloud and youtube.
There is still an enhancement necessary in order to provide a stop mechanism as soon as an internet disconnect is noticed.

Test patch: 9aadefe7d0ce639cb96c229e389178ba447179af

**Comment by R3DST0RM** [comment]
Issues finally finished/fixed with commit: 11a0c1a8bf88b0e23dd5eb1de5841f5f7cc3cc25
